### ISSUE TITLE
Moving env vars from `docker-compose.yaml` into `.env`

### ISSUE THREAD

**Issue by EvitanRelta** [CS3219-AY2324S1/ay2324s1-course-assessment-g23#142]
Perhaps we should move these environment variables into `.env` file, instead of putting them in the `docker-compose.yaml`

```yaml
  api_gateway:
    build: ./backend_services/api_gateway
    container_name: api_gateway
    networks:
      - client-side
      - backend-apis
    ports:
      - 8000:8000
    environment:
      - USERS_SERVICE_HOST=users_api
      - SESSIONS_SERVICE_HOST=users_api
      - QUESTIONS_SERVICE_HOST=questions_api
      - MATCHING_SERVICE_HOST=matching_api
      - API_PORT=8000
```
